
all:
	ajc Customer.java CompanySystem.java \
		AbstractContract.java	\
		ContractManager.java \
		ContractBrokeException.java \
		CompanySystemContractManager.java \
		ContractCompanySystem.java \
		Main.java

clean:
	rm -f *.class
